@startuml ModelUML

'Interfacce per pattern ECS
interface Component{
}
interface System{
    ~ update(sim:Simulation):T[]
}
'Classi Component
class PositionComponent implements Component{
    ~double x
    ~double y
    ~double z
}
class VelocityComponent implements Component{
    ~double vx
    ~double vy
    ~double vz
}
class AccelerationComponent implements Component{
    ~double ax
    ~double ay
    ~double az
}
class MassComponent implements Component{
    ~double mass
}
class NameComponent implements Component{
    ~String name
}
'ComponentManager (gestione dei componenti)
class ComponentManager {

        - int size
        - int lastIndex
        - boolean isFull()
        - boolean isScarce()
        - grow():void 
        - resize(newSize:int):void 
        - shrink():void 
        + addComponent(component:Class<T>):void
        ~ <T extends Component> getComponent(component:Class<T>):T[] 
        + <T extends Component> getSafeComponent(component:Class<T>):T[]
        + addEntity(Component... components):int 
        + deleteEntity(int entityId):void 
    }
    ComponentManager [Class] --> "*" Component : - storage

    'Simulation (Contiene tutti i dati per istanza di simulazione)
    class Simulation {
        - double timeStep
        - LocalDateTime currentDate
        - LocalDateTime targetDate
        - double currentTime
        - double targetTime
    }
    Simulation "1" *-- "1" ComponentManager : - componentManager
    Simulation "1" o-- "many" System : - systemsQueue
    System --> Simulation : updates
    'Sistemi motore fisico
    class NewtonLawSystem implements System{
        - double G
        ~ update(sim:Simulation):void
    }
    class IntegrationSystem implements System{
        ~ update(sim:Simulation):void
    }
    'Builder pattern per creare istanze di simulazione


@enduml
