@startuml ModelUML

'Interfacce per pattern ECS
interface Component{
}
interface System{
    ~void update(Simulation sim)
}
'Classi Component
class PositionComponent implements Component{
    ~double x
    ~double y
    ~double z
}
class VelocityComponent implements Component{
    ~double vx
    ~double vy
    ~double vz
}
class AccelerationComponent implements Component{
    ~double ax
    ~double ay
    ~double az
}
class MassComponent implements Component{
    ~double mass
}
class NameComponent implements Component{
    ~String name
}
'ComponentManager (gestione dei componenti)
class ComponentManager {

        - int size
        - int lastIndex
        - boolean isFull()
        - boolean isScarce()
        - void grow()
        - void resize(int newSize)
        - void shrink()
        + void addComponent(Class<T> component)
        ~ <T extends Component> T[] getComponent(Class<T> component)
        + <T extends Component> T[] getSafeComponent(Class<T> component)
        + int addEntity(Component... components)
        + void deleteEntity(int entityId)
    }
    ComponentManager [Class] --> "*" Component : - storage

    'Simulation (Contiene tutti i dati per istanza di simulazione)
    class Simulation {
        - double timeStep
        - LocalDateTime currentDate
        - LocalDateTime targetDate
        - double currentTime
        - double targetTime
    }
    Simulation "1" *-- "1" ComponentManager : - componentManager
    Simulation "1" o-- "many" System : - systemsQueue
    System --> Simulation : updates

@enduml
